name: Setup Environment
on:
  schedule:
    - cron: '0 6 1-31 * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      - name: Setup Environment and Start Testing
        run: |
          python3 setup.py full
          python3 kwtesting/run.py
